# Generated by Django 6.0 on 2026-01-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='urlYoutube',
            field=models.TextField(blank=True, null=True),
        ),
    ]
